[package]
name = "video_cam"
version = "0.1.0"
edition = "2024"

[dependencies]
opencv = { version = "0.97.2", default-features = false, features = [
    "clang-runtime",
    "imgproc",
    "imgcodecs",
    "videoio",
    "highgui",
    "dnn",
] }
ndarray = "0.15"
image = "0.24"
webrtc = "0.10"
anyhow = "1"
tokio = { version = "1", features = ["full"] }
sqlx = { version = "0.7", features = ["runtime-tokio", "postgres", "macros"] }
